# Generated by Django 5.2.6 on 2025-10-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0002_questionnaire_typeprofile_question_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeprofile',
            name='career_suggestions',
            field=models.TextField(blank=True, verbose_name='职业建议'),
        ),
        migrations.AddField(
            model_name='typeprofile',
            name='communication_style',
            field=models.TextField(blank=True, verbose_name='沟通风格'),
        ),
        migrations.AddField(
            model_name='typeprofile',
            name='decision_making',
            field=models.TextField(blank=True, verbose_name='决策方式'),
        ),
        migrations.AddField(
            model_name='typeprofile',
            name='emotional_expression',
            field=models.TextField(blank=True, verbose_name='情感表达'),
        ),
        migrations.AddField(
            model_name='typeprofile',
            name='interpersonal_relations',
            field=models.TextField(blank=True, verbose_name='人际关系'),
        ),
        migrations.AddField(
            model_name='typeprofile',
            name='learning_style',
            field=models.TextField(blank=True, verbose_name='学习方式'),
        ),
        migrations.AddField(
            model_name='typeprofile',
            name='life_philosophy',
            field=models.TextField(blank=True, verbose_name='生活哲学'),
        ),
        migrations.AddField(
            model_name='typeprofile',
            name='personality_traits',
            field=models.TextField(blank=True, verbose_name='性格特点'),
        ),
        migrations.AddField(
            model_name='typeprofile',
            name='stress_management',
            field=models.TextField(blank=True, verbose_name='压力管理'),
        ),
        migrations.AddField(
            model_name='typeprofile',
            name='work_style',
            field=models.TextField(blank=True, verbose_name='工作风格'),
        ),
    ]
